# fly.toml file generated for pdns-auth on 2023-01-04T15:23:52+01:00

app = "pdns-auth"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PDNSCONF_DEFAULT_SOA = "ns1.berndklaus.cloud. berndklaus.cloud. 0 10800 3600 604800 3600"
  PDNSCONF_FLYIO_MAINREGION = "cdg"
  PDNSCONF_GPGSQL_DBNAME = "pdns"
  PDNSCONF_GPGSQL_PORT = "5432"
  PDNSCONF_GPGSQL_READPORT = "5433"
  PDNSCONF_GPGSQL_USER = "pdns_auth"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  private_network= true

[metrics]
  path = "/metrics"
  port = 80

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 60
    soft_limit = 50
    type = "connections"

  [[services.ports]]
    force_https = false
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[services]]
  internal_port = 53
  protocol = "udp"

  [[services.ports]]
    port = 53

[[services]]
  internal_port = 53
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 100
    soft_limit = 80
    type = "connections"

  [[services.ports]]
    port = 53
    
  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
